#!/usr/bin/env bash

# lsd2: Script that accepts two arguments and lists  the files in that directory.
# Usage: ./lsd2 {folder} {options}
# options:
#   sort: sorted alphabatically ASC
#   rsort: sorted alphabatically DESC
#   time: sorted by time ASC
#   rtime: sorted by time DESC
#   size: sorted by size ASC
#   rsize: sorted by size DESC



if [ $# -eq 0 ]
  then
    echo "No arguments supplied only one directory argument should provided"


elif [ $# -gt 2 ] || [ $#  -le 1 ]
  then
    echo "in order to execute the script you need  two  agrument
          first argument directory and the second one is an  option"

fi

  case $2  in
        -t | -time )          
                                ls -lt $1
                                ;;
        -rt | -rtime )         
                                ls -rlt $1
                                ;;
        -S | -size )
                                ls -lS $1
                                ;;
        -rS | -rsize )
                                ls -rlS $1
                                ;;
       
        * )                   
                               exit
                                ;;

    esac
