#!/usr/bin/env bash

# lsd3: Script that accepts one argument which is a directory
# Usage: ./lsd3 {folder}
# The result should be the list of each file where the colors of the files alternate 
# between regular color and red.


RED=`tput setaf 1`
RESET=`tput sgr0`

ls $1 | sort -f  | while read file
do
  echo -e "${RED}$file"
  read file
  echo -e "${RESET}$file"
done
